/* Generated By:JavaCC: Do not edit this line. GramaticaConstants.java */
//analiza el codigo.txt

package Analizador;


/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface GramaticaConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int START = 5;
  /** RegularExpression Id. */
  int END = 6;
  /** RegularExpression Id. */
  int PR_INTERGER = 7;
  /** RegularExpression Id. */
  int PR_DECIMAL = 8;
  /** RegularExpression Id. */
  int PR_TXT = 9;
  /** RegularExpression Id. */
  int PR_PRINT = 10;
  /** RegularExpression Id. */
  int PR_KEYBOARD = 11;
  /** RegularExpression Id. */
  int PR_IF = 12;
  /** RegularExpression Id. */
  int PR_ELSE = 13;
  /** RegularExpression Id. */
  int PR_FOR = 14;
  /** RegularExpression Id. */
  int PR_WHILE = 15;
  /** RegularExpression Id. */
  int PR_DO = 16;
  /** RegularExpression Id. */
  int PR_SWITCH = 17;
  /** RegularExpression Id. */
  int PR_BREAK = 18;
  /** RegularExpression Id. */
  int PR_RETURN = 19;
  /** RegularExpression Id. */
  int PR_CASE = 20;
  /** RegularExpression Id. */
  int PR_DEFAULT = 21;
  /** RegularExpression Id. */
  int INCREMENT = 22;
  /** RegularExpression Id. */
  int DECREMENT = 23;
  /** RegularExpression Id. */
  int IQUAL_TO = 24;
  /** RegularExpression Id. */
  int SUM = 25;
  /** RegularExpression Id. */
  int MINUS = 26;
  /** RegularExpression Id. */
  int MULTIPLY = 27;
  /** RegularExpression Id. */
  int DEVIDE = 28;
  /** RegularExpression Id. */
  int REMEAINDER = 29;
  /** RegularExpression Id. */
  int IQUAL = 30;
  /** RegularExpression Id. */
  int DELIMITADOR = 31;
  /** RegularExpression Id. */
  int DOBLE_POINT = 32;
  /** RegularExpression Id. */
  int DOTE = 33;
  /** RegularExpression Id. */
  int QUOTES = 34;
  /** RegularExpression Id. */
  int COM = 35;
  /** RegularExpression Id. */
  int BRACE_OPEN = 36;
  /** RegularExpression Id. */
  int BRACE_CLOSE = 37;
  /** RegularExpression Id. */
  int PARENTHESIS_OPEN = 38;
  /** RegularExpression Id. */
  int PARENTHESIS_CLOSE = 39;
  /** RegularExpression Id. */
  int BRACKET_OPEN = 40;
  /** RegularExpression Id. */
  int BRACKET_CLOSE = 41;
  /** RegularExpression Id. */
  int SMALLER_THAN = 42;
  /** RegularExpression Id. */
  int GREATER_THAN = 43;
  /** RegularExpression Id. */
  int ID = 44;
  /** RegularExpression Id. */
  int NUMBER = 45;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"Start\"",
    "\"End\"",
    "\"varInt\"",
    "\"varDecimal\"",
    "\"varChar\"",
    "\"print\"",
    "\"scanner\"",
    "\"if\"",
    "\"ifnot\"",
    "\"for\"",
    "\"while\"",
    "\"do\"",
    "\"switch\"",
    "\"break\"",
    "\"return\"",
    "\"case\"",
    "\"default\"",
    "\"++\"",
    "\"--\"",
    "\"==\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"=\"",
    "\";\"",
    "\":\"",
    "\".\"",
    "\"\\\"\"",
    "\",\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"<\"",
    "\">\"",
    "<ID>",
    "<NUMBER>",
  };

}
